swagger: '2.0'
info:
  title: Shipping MC
  version: "0.1"
  description: Shipping Microservice
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /order/create:
    post:
      tags: [ Order ]
      operationId: endpoints.order_endpoints.create_order
      parameters:
        - $ref: '#/parameters/createorder_body'
      responses:
        200:
          description: Return status
        409:
          description: Already exists

  /courier/create:
    post:
      tags: [ Courier ]
      operationId: endpoints.courier_endpoints.add_courier
      parameters:
        - $ref: '#/parameters/courier_body'
      responses:
        200:
          description: Return status
        409:
          description: Already exists

  /order/user/{id}:
    get:
      tags: [ Order ]
      operationId: endpoints.order_endpoints.find_user_order
      parameters:
        - $ref: '#/parameters/id'
      responses:
        200:
          description: Return order
        404:
          description: Does not exist

  /order/edit/{id}:
    put:
      tags: [ Order ]
      operationId: endpoints.order_endpoints.edit_order
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/createorder_body'
      responses:
        200:
          description: Return order
        404:
          description: Not found

  /courier/edit/{id}:
    put:
      tags: [ Courier ]
      operationId: endpoints.courier_endpoints.edit_courier
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/courier_body'
      responses:
        200:
          description: Return courier
        404:
          description: Not found

  /courier/listall:
    get:
      tags: [ Courier ]
      operationId: endpoints.courier_endpoints.list_couriers
      responses:
        200:
          description: Return list of Couriers
        404:
          description: Does not exist

  /order/listall:
    get:
      tags: [ Order ]
      operationId: endpoints.order_endpoints.list_orders
      responses:
        200:
          description: Return list of Couriers
        404:
          description: Does not exist

  /order/delete/{id}:
    delete:
      tags: [ Order ]
      operationId: endpoints.order_endpoints.delete_order
      parameters:
        - $ref: '#parameters/id'
      responses:
        200:
          description: Order is deleted
        404:
          description: Not found

  /courier/delete/{id}:
    delete:
      tags: [ Courier ]
      operationId: endpoints.courier_endpoints.delete_courier
      parameters:
        - $ref: '#parameters/id'
      responses:
        200:
          description: Courier is deleted
        404:
          description: Not found


parameters:
  id:
    name: id
    description: User identification
    in: path
    type: integer
    required: true

  createorder_body:
    name: createorder_body
    description: Creating an order
    in: body
    schema:
      required:
        - id
        - delivery_time
        - courier_assigned
        - priority
        - order_state
        - description

      properties:
        id:
          type: integer
        delivery_time:
          type: string
        priority:
          type: boolean
        description:
          type: string
        courier_assigned:
          type: integer
        order_state:
          type: string

  courier_body:
    name: courier_body
    description: Input for courier
    in: body
    schema:
      required:
        - id
        - name
        - location
      properties:
        id:
          type: integer
        name:
          type: string
        location:
          type: string
