swagger: '2.0'
info:
  title: Shipping MC
  version: "0.1"
  description: Shipping Microservice
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /create_order/:
    post:
      tags: [ Order ]
      operationId: app.create_order
      parameters:
        - $ref: '#/parameters/createorder_body'
      responses:
        200:
          description: Return status
        409:
          description: Already exists

  /add_courier/:
    post:
      tags: [ Courier ]
      operationId: app.add_courier
      parameters:
        - $ref: '#/parameters/courier_body'
      responses:
        200:
          description: Courier added
        409:
          description: Already exists

  /order/user/{user_id}:
    get:
      tags: [ Order ]
      operationId: app.find_user_order
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: return order
        404:
          description: Does not exist

    /order/change/{order_id}:
      get:
        tags: [ Order ]
        operationId: app.edit_order
        parametars:
          - $ref: '#/parameters/order_id'
          - $ref: '#/parameters/courier_body'
        responses:
          200:
            description: return order
          404:
            description: not found


parameters:
  createorder_body:
    name: createorder_body
    description: Creating an order
    in: body
    schema:
      required:
        - user_id
        - delivery_time
        - priority
      properties:
        user_id:
          type: integer
        delivery_time:
          type: string
        priority:
          type: boolean

  user_id:
    name: user_id
    description: User identification
    in: path
    type: integer
    required: true

  order_id:
    name: order_id
    description: Order identification
    in: path
    type: integer
    required: true


  courier_body:
    name: courier_body
    description: Input for courier
    in: body
    schema:
      required:
        - id
        - name
        - location
      properties:
        id:
          type: integer
        name:
          type: string
        location:
          type: string
