swagger: '2.0'
info:
  title: Shipping MC
  version: "0.1"
  description: Shipping Microservice
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /create_order/:
    post:
      tags: [ Order ]
      operationId: app.create_order
      parameters:
        - $ref: '#/parameters/createorder_body'
      responses:
        200:
          description: Return status
        409:
          description: Already exists

  /add_courier/:
    post:
      tags: [ Courier ]
      operationId: app.add_courier
      parameters:
        - $ref: '#/parameters/courier_body'
      responses:
        200:
          description: Return status
        409:
          description: Already exists

  /order/user/{userId}:
    get:
      tags: [ Order ]
      operationId: app.find_user_order
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        200:
          description: Return order
        404:
          description: Does not exist

  /orderEdit/{orderId}:
    put:
      tags: [ Order ]
      operationId: app.edit_order
      parameters:
        - $ref: '#/parameters/orderId'
        - $ref: '#/parameters/createorder_body'
      responses:
        200:
          description: Return order
        404:
          description: Not found

  /courierEdit/{courierId}:
    put:
      tags: [ Courier ]
      operationId: app.edit_courier
      parameters:
        - $ref: '#/parameters/courierId'
        - $ref: '#/parameters/courier_body'
      responses:
        200:
          description: Return courier
        404:
          description: Not found

parameters:

  userId:
    name: userId
    description: User identification
    in: path
    type: integer
    required: true

  orderId:
    name: orderId
    description: Order identification
    in: path
    type: integer
    required: true

  courierId:
    name: courierId
    description: Courier identifaction
    in: path
    type: integer
    required: true

  createorder_body:
    name: createorder_body
    description: Creating an order
    in: body
    schema:
      required:
        - orderId
        - delivery_time
        - courier_assigned
        - priority
        - order_state
        - description

      properties:
        orderId:
          type: integer
        delivery_time:
          type: string
        priority:
          type: boolean
        description:
          type: string
        courier_assigned:
          type: integer
        order_state:
          type: string

  courier_body:
    name: courier_body
    description: Input for courier
    in: body
    schema:
      required:
        - id
        - name
        - location
      properties:
        id:
          type: integer
        name:
          type: string
        location:
          type: string
