"""empty message

Revision ID: 07517118016b
Revises: 57dacd2dbfaa
Create Date: 2021-04-23 23:22:23.345943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07517118016b'
down_revision = '57dacd2dbfaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('courier_assigned', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Boolean(), nullable=False),
    sa.Column('order_state', sa.Enum('Approved', 'Accepted', 'Preparing', 'ReadyForPickUp', 'PickedUp', 'Delivered', name='orderstate'), nullable=True),
    sa.Column('delivery_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('courier')
    # ### end Alembic commands ###
