"""empty message

Revision ID: bd4dd3c4d28f
Revises: f3b072a3ee9d
Create Date: 2021-04-26 13:55:54.922837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4dd3c4d28f'
down_revision = 'f3b072a3ee9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('userId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'userId')
    # ### end Alembic commands ###
